# Generated by Django 4.1 on 2022-11-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits_and_pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_adoptable',
            field=models.BooleanField(default=1),
        ),
    ]
