# Generated by Django 4.1 on 2022-11-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits_and_pets', '0002_pet_age_pet_is_adoptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='is_ripe',
            field=models.BooleanField(default=1),
        ),
    ]
