# Generated by Django 4.1 on 2022-11-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruits_and_pets', '0003_fruit_is_ripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=40)),
                ('is_squeaky', models.BooleanField(default=1)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_toys', to='fruits_and_pets.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pets', to='fruits_and_pets.owner'),
            preserve_default=False,
        ),
    ]
